### ISSUE TITLE
Idea Template

### ISSUE THREAD

**Issue by esip-lab** [ESIPFed/GSoC#1]
**Idea**
Explain the project and _how_ a student would engage. 

**Skills Needed**
List of skills needed, e.g. jupyter, kubernetes, dask, xarray, zarr, python

**Mentors**
Annie Burgess, ESIP Federation

More information on how to write a good idea summary here: https://google.github.io/gsocguides/mentor/making-your-ideas-page

**Comment by Gautamshahi** [comment]
@abburgess any suggestions for the Idea development?
