### ISSUE TITLE
National Water Model data visualization

### ISSUE THREAD

**Issue by jreadey** [ESIPFed/GSoC#2]
**Idea**

National Water Model data visualization

Create an AJAX WebUI that enables visualization of the entire 20TB National Water Model dataset (http://water.noaa.gov/about/nwm). 

There is a viewer for pre-computed National Water Model data at http://water.noaa.gov/tools/nwm-image-viewer, but now that the data is available on AWS, there's the potential to interactively explore the entire dataset.  

This viewer for the National Renewable Energy lab WIND dataset (also many TB), illustrates the concept: https://nrel.github.io/hsds-viz/  (see screen grab below).   More info on the NREL viewer at https://www.nrel.gov/grid/wind-toolkit.html.  

**Skills Needed**

JavaScript, HTML, AJAX, data visualization

**Mentors**

- John Readey, The HDF Group
- Rich Signell,  USGS

![2018-01-23_6-42-11](https://user-images.githubusercontent.com/1872600/35274107-e4e24312-0008-11e8-8259-6eb906baea1b.jpg)

**Comment by lieberjosh** [comment]
Harvard Center for Geographic Analysis is developing a system for analyzing and viewing NWM output data using GPU-powered data access and rendering (MapD). We'd also be interested in supporting student development of visualization applications on top of this. While we have captured our own store of 6 weeks of NWM output netcdf datafiles, access to an already created S3 store would be helpful if such a repository exists.

**Comment by jreadey** [comment]
@lieberjosh - that sounds very interesting.  Does MapD already support data stored in HDF5?

**Comment by lieberjosh** [comment]
Not yet. A possible enhancement. We presently do conversion and processing of the output files before loading.

**Comment by jjmachan** [comment]
hi, 
I would like to work on this project. I am experienced in  working with web apps and build a few using angular. I've gone through the docs and have a rough idea. Can I start working on this?

**Comment by rsignell-usgs** [comment]
https://www.prnewswire.com/news-releases/mapd-to-collaborate-with-the-center-for-geographic-analysis-at-harvard-university-to-accelerate-research-with-gpus-300505042.html

@lieberjosh , does Harvard have anything to look at yet?

**Comment by lieberjosh** [comment]
We’re still waiting on hardware to be installed at the Mass Open Cloud and for a new version of MapD supporting more graphics types, but we have a test dataset loaded on an AWS instance. Hope to have something more usable in 1-2 months. That bitcoin-mining is stiff competition for GPU cards.

—Josh

**Comment by lieberjosh** [comment]
Is there indeed an accessible NWM S3 archive? Haven’t found any information about this.

**Comment by SETIADEEPANSHU** [comment]
I am interested in this project , how can I start?

**Comment by rsignell-usgs** [comment]
Ideas for what we would visualize
* soil moisture visualization that overlays stream flow with soil saturation (from @dblodgett-usgs)
* interactive, real-time ability to produce [streamflow animations on a map](https://www.youtube.com/watch?v=lbA2KoYSEsg&feature=youtu.be&t=16)

**Comment by esip-lab** [comment]
@jreadey or @rsignell-usgs any chance you'd like to update and open this back up for 2019 GSoC?
