### ISSUE TITLE
New Project proposal

### ISSUE THREAD

**Issue by DenuwanLiyanage** [ESIPFed/GSoC#24]
Hi, I'm Denuwan from University of Moratuwa Sri Lanka.
I'm trying to find a method to identifying the diseases which occurs in cereals using satellite. If I do this as a project can you help me to
find a mentor to my project? Please be kind to give a response.
Thank You for you time.

**Comment by lewismc** [comment]
Hi @DenuwanLiyanage can you please forwarded your message to the ESIP Agriculture community
wiki page - http://wiki.esipfed.org/index.php/Agriculture_and_Climate
mailing list - http://lists.esipfed.org/mailman/listinfo/esip-agclimate
Thanks

**Comment by DenuwanLiyanage** [comment]
Ok. Thank you for the response.

**Comment by DenuwanLiyanage** [comment]
Can you tell me how can I contact someone in Agriculture community ? Is that ok to post a mail on mail list?

**Comment by DenuwanLiyanage** [comment]
Can you tell who is the mentor for this project? I'm interesting about this project.

**Comment by Kirishikesan** [comment]
I am also trying to get into dealing with satellite images. I'll send you any resources that I can find about this. best of luck

**Comment by esip-lab** [comment]
@DenuwanLiyanage a mentor would have to come from the ESIP community for this project to proceed. Lewis made good suggestions about our community groups that may have interest.
