### ISSUE TITLE
Create a test suite and linter tooling for CovJSON 

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/GSoC#26]
# Introduction
[CoverageJSON](https://covjson.org/) (typically shortened to CovJSON) is a format for encoding coverage data like grids, time series, and vertical profiles, distinguished by the geometry of their spatiotemporal domain. A CoverageJSON object represents a domain, a range, a coverage, or a collection of coverages. A range in CoverageJSON represents coverage values. A coverage in CoverageJSON is the combination of a domain, parameters, ranges, and additional metadata. A coverage collection represents a list of coverages.

# Project Description
This project seeks to develop and provide 
- **A test suite for CovJSON**: existing test suites from which motivation can be drawn exist for [JSON-LD](https://w3c.github.io/json-ld-api/tests/), [RDFa](http://rdfa.info/test-suite/) and [Microformats](https://github.com/microformats/tests).
- **Processor Conformance**: which would report processor conformance (e.g. OPeNDAP Hyrax, THREDDS, etc.) for CovJSON and related specifications according to the requirements of the [Evaluation and Report Language (EARL) 1.0 Schema](https://www.w3.org/TR/EARL10-Schema/)

# Mentors
@lewismc , NASA JPL
@jonblower, Institute for Environmental Analytics

# Required Knowledge
Knowledge of environmental observation data which captures structures such as grids, time series, and vertical profiles, distinguished by the geometry of their spatiotemporal domain. Understanding what these data structures are is fundamental to achieving excellence in this project, that is to say, working with that kind of data should be something you are already interested in and experience in.

**Comment by faraazshah** [comment]
I am interested!
Tried to contact you since @lewismc  on slack etc.

**Comment by lewismc** [comment]
hi @shfrz great, please start working on a proposal. Is there anything you need clarification on regrarding the above proposal?

**Comment by faraazshah** [comment]
Thanks a lot for replying!
I am really sorry that I showed up late.
But the best part is that during the GSoC period, I would be available full time 'cause I have no commitments for the college as I would be on a full two month vacation!

**Comment by lewismc** [comment]
@shfrz as we spoke about offline the final date for submitting a proposal is tomorrow. If you would like to be considered then you MUST submit a proposal by tomorrow this is mandated by Google. Thank you

**Comment by faraazshah** [comment]
Sure! Trying hard !
"Only one, but ripe" :)

**Comment by faraazshah** [comment]
Submitted the draft proposal for review. Hope you checked that!

**Comment by OLavrik** [comment]
Hi @lewismc, 

So interesting and knowledgeful tasks. I really like it and already submitted a proposal.

I wish for further collaboration.

Regards,
Olya Lavrichenko

**Comment by lewismc** [comment]
Thank you all for your proposals and your interest in ESIP. Unfortunately this project was not selected this year.

**Comment by faraazshah** [comment]
Really heartbreaking ...
