### ISSUE TITLE
Community Ontology Repository (COR) Feature Updates

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/GSoC#3]
# Idea
The ESIP [COR](http://cor.esipfed.org/) is a custom deployment of the [MMISW ORR Software](https://github.com/mmisw/orr) which provides a data hub for semantic technologists across ESIP.
In addition to the open issues for the ORR [frontend](https://github.com/mmisw/orr-portal/issues) and [backend](https://github.com/mmisw/orr-ont/issues), there are a number of unlogged feature requests including [reasoning](http://www.obitko.com/tutorials/ontologies-semantic-web/reasoning.html), [inference](https://www.w3.org/standards/semanticweb/inference), development of a reporting API, etc. This project would involve heavy development of the ORR software to address the above feature requests and open issues.

# Skills Needed
Scala, JavaScript, Shell

# Mentors
Lewis John McGibbney, NASA JPL
Carlos Rueda, MBARI

**Comment by jaskirat1208** [comment]
I would like to contribute to it. Please guide me how to start.

**Comment by lewismc** [comment]
Hello @jaskirat1208 thank you for registering your interest. ESIP has been selected as a particpating organization so you should scope out the guidelines and timeline over at the GSoC site.
As it turns out, [Student Applications open March 12, 2018 at 09:00 (PDT)](https://summerofcode.withgoogle.com/get-started/), however I would encourage you to begin getting involved in COR development before then.
@carueda I think this is a good time for us to begin prioritizing 'new-comer' issues to COR development... can you assist here? Thanks

**Comment by carueda** [comment]
Hi @jaskirat1208 yes, thanks for your interest.  Let us know as you explore and see potential tasks and tell us perhaps about any preference in terms of backend or frontend focus, etc.

@lewismc Lewis, yes, I'll start by adding the 'good first issue' label in the ORR issue trackers and looking into using it in appropriate entries.  And yes, we need to enter those unlogged feature requests.

**Comment by jaskirat1208** [comment]
@carueda @lewismc  could you please give me some easy to start tasks that I can do to start with?

**Comment by vaibhavchellani** [comment]
@carueda @lewismc i would like to work on this as well . I was looking forward to developing COR and was searching for repos in the organisation to view the existing issues . if you could direct me to the correct repo it would be great . 
Thanks !

**Comment by carueda** [comment]
Please see the Idea section.

**Comment by vaibhavchellani** [comment]
@carueda apologies . thank you

**Comment by carueda** [comment]
Hi @jaskirat1208 @vaibhavchellani @lewismc and everyone interested.

I was intending to provide some additional information but it has taken a bit longer than planned, sorry.

So, the parent space is https://github.com/mmisw/

The key repositories are:

### https://github.com/mmisw/orr

This one is mainly to build the integrated ORR system, which involves "dockerization" of the ORR itself and use of the docker images for MongoDB and AllegroGraph.  We don't currently have any specific pressing needs here.

### https://github.com/mmisw/orr-ont

This is the backend service. Written in Scala it uses http://scalatra.org/ as the web toolkit.

A bit challenging depending on prior experience but certainly feasible task is https://github.com/mmisw/orr-ont/issues/47, where in particular we are interested in using a much more active and mature web toolkit as well as facilitate the automatic generation of the OpenAPI specification (which we already use) for the REST API. Among the various benefits, with this in place we would also make the automatic generation of client libraries (eg., python) more reliable.

Another important issue is https://github.com/mmisw/orr-ont/issues/64, about the reasoning capabilities of the SPARQL endpoint and possible use of alternative underlying triple stores, ideally open-source.

 I also just marked https://github.com/mmisw/orr-ont/issues/63 as a "good first issue."

### https://github.com/mmisw/orr-portal

This is the frontend. Written in Javascript it uses https://angularjs.org/ as the web framework.

A common enhancement request has been about the user-friendlier display of vocabularies, for example as captured at https://github.com/mmisw/orr-ont/issues/57; note, on the backend repo tracker. although  it is possible that improvements here may involve both frontend and backend components.

Other related usability issues:

- https://github.com/mmisw/orr-portal/issues/68
- https://github.com/mmisw/orr-portal/issues/92

### Other possible tasks?

There are other various aspects/issues that can be addressed as well depending on the applicant interests and experience, in particular regarding semantics and its proper use in the ORR.  If you are interested in these or other aspects by exploring the existing entries in the trackers, do please let us know so we can coordinate.

**Comment by lewismc** [comment]
@jaskirat1208 any updates here?
